// This is file to test api

######################### Environment variable ##########################x
@userToken = afbb84f0ed869bf3e1fb7a6e7a09ae1067ea54e8
@adminToken = insert adminToken here
@baseUserUrl = http://127.0.0.1:8000/api/v1/bbook/users
@baseProductUrl = http://127.0.0.1:8000/api/v1/bbook/products
@basePaymentUrl = http://127.0.0.1:8000/api/v1/bbook/payments


############################## USER ###############################

### GET ALL USER
GET {{baseUserUrl}}/getAll 
Content-Type: application/json
Authorization: Bearer {{userToken}}

### GET USER INFO
GET {{baseUserUrl}}/info
Content-Type: application/json
Authorization: Token {{userToken}}

### REGISTER
POST {{baseUserUrl}}/register
Content-Type: application/json

{
    "first_name": "nguyen",
    "last_name": "van anh",
    "username": "nguyenanh",
    "email": "nguyenanh@gmail.com",
    "password": "Nguyenanh123"
}

### LOGIN
POST {{baseUserUrl}}/login
Content-Type: application/json

{
    "username": "nguyenanh@gmail.com",
    "password": "Nguyenanh123"
}

### LOGOUT
GET {{baseUserUrl}}/logout
Content-Type: application/json
Authorization: Bearer {{userToken}}

####################################################################

############################ PRODUCT ###############################

### GET ALL GENRE 
GET {{baseProductUrl}}/genres

### CREATE GENRE
POST {{baseProductUrl}}/genres
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "sinh": "sinh"
}

### RETRIEVE GENRE
GET {{baseProductUrl}}/genres/sach-thieu-nhi

### UPDATE GENRE
PUT {{baseProductUrl}}/genres/sach-thieu-nhi
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    
}

### DELETE GENRE
DELETE  {{baseProductUrl}}/genres/sach-thieu-nhi

####################################################################
############################ PAYMENT ###############################

### GET ALL USER ORDER 
GET {{basePaymentUrl}}/order
Content-Type: application/json
Authorization: Bearer {{userToken}}

### CREATE ORDER
POST {{basePaymentUrl}}/order
Content-Type: application/json
Authorization: Bearer {{userToken}}

### GET ORDER DETAIL
GET {{basePaymentUrl}}/order/1
Content-Type: application/json
Authorization: Bearer {{userToken}}

### UPDATE ORDER
PUT {{basePaymentUrl}}/order/1
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "ship_date": "",
    "ship_place": "",
    "note" : "",
    "is_paid": true,
    "paid_at": "",
    "product": [
    {
        "book" : 1,
        "quantity" : 1,
    },
    {
        "book" : 5,
        "quantity" : 2
    }
    ]
}
### DELETE ORDER
DELETE  {{basePaymentUrl}}/order/1

### GET ALL ORDER