// This is file to test api

######################### Environment variable ##########################x
@userToken = 89949cc62719d22c50acac73c9b8f5ec814c14dd
@adminToken = 101f0009ea536ba8fa50877e691048086ec29744
@baseUserUrl = http://127.0.0.1:8000/api/v1/bbook/users
@baseProductUrl = http://127.0.0.1:8000/api/v1/bbook/products
@basePaymentUrl = http://127.0.0.1:8000/api/v1/bbook/payments


############################## USER ###############################

### GET ALL USER
GET {{baseUserUrl}}/getAll 
Content-Type: application/json
Authorization: Token {{userToken}}

### GET USER INFO
GET {{baseUserUrl}}/info
Content-Type: application/json
Authorization: Token {{userToken}}

### REGISTER
POST {{baseUserUrl}}/register
Content-Type: application/json

{
    "first_name": "nguyen",
    "last_name": "van anh",
    "username": "nguyenanh",
    "email": "nguyenanh@gmail.com",
    "password": "Nguyenanh123"
}

### LOGIN
POST {{baseUserUrl}}/login
Content-Type: application/json

{
    "username": "nguyenanh@gmail.com",
    "password": "Nguyenanh123"
}

### ADMIN LOGIN
POST {{baseUserUrl}}/login
Content-Type: application/json

{
    "username": "admin_bbook@gmail.com",
    "password": "admin131"
}


### LOGOUT
GET {{baseUserUrl}}/logout
Content-Type: application/json
Authorization: Token {{userToken}}

####################################################################

############################ PRODUCT ###############################

### GET ALL GENRE 
GET {{baseProductUrl}}/genres

### CREATE GENRE
POST {{baseProductUrl}}/genres
Content-Type: application/json
Authorization: Token {{adminToken}}

{
    "sinh": "sinh"
}

### RETRIEVE GENRE
GET {{baseProductUrl}}/genres/sach-thieu-nhi

### UPDATE GENRE
PUT {{baseProductUrl}}/genres/sach-thieu-nhi
Content-Type: application/json
Authorization: Token {{adminToken}}

{
    
}

### DELETE GENRE
DELETE  {{baseProductUrl}}/genres/sach-thieu-nhi

############################# AUTHOR ###############################
### GET ALL AUTHOR 
GET {{baseProductUrl}}/authors

### CREATE AUTHOR
POST {{baseProductUrl}}/authors
Content-Type: application/json
Authorization: Token {{adminToken}}

{
    "sinh": "sinh"
}

### RETRIEVE AUTHOR
GET {{baseProductUrl}}/authors/sach-thieu-nhi

### UPDATE AUTHOR
PUT {{baseProductUrl}}/authors/sach-thieu-nhi
Content-Type: application/json
Authorization: Token {{adminToken}}

{
    
}

### DELETE AUTHOR
DELETE  {{baseProductUrl}}/authors/sach-thieu-nhi

####################################################################

############################# BOOK #################################
###
GET {{baseProductUrl}}/search?title=m

### GET ALL BOOK WITH QUERY PARAM
GET {{baseProductUrl}}/books?limit=20&offset=10

### GET BOOK DYNAMIC
GET {{baseProductUrl}}/books

### GET BOOK WITH SORT DESC
Đối với sort, có 4 options: desc_alphabet, asc_alphabet, asc_alphabet, max_price
set vào params order của route {{baseProductUrl}}/books
###
GET {{baseProductUrl}}/books?order=max_price&limit=10&offset=10

### GET ALL BOOK ID
GET {{baseProductUrl}}/all-book-id

### GET BOOK FROM LIST ID
POST {{baseProductUrl}}/all-book-id
Content-Type: application/json

{
    "list_recommend_book": [1,2,3,4,5,6,9,7]
}

###  GET BOOKS WITH GENRE 
GET {{baseProductUrl}}/genres/sach-thieu-nhi/books

### 
GET {{baseProductUrl}}/genres/sach-thieu-nhi/books?limit=24&offset=0

###  GET BOOKS WITH AUTHOR 
GET {{baseProductUrl}}/authors/ahn-yujin/books

### 
GET {{baseProductUrl}}/authors/ahn-yujin/books?limit=24&offset=24


### CREATE BOOK
POST {{baseProductUrl}}/books
Content-Type: application/json
Authorization: Token {{adminToken}}

{
    "genre": 1,
    "author": 1,
    "title": "Tiếng chim hót trong bụi mận gai",
    "thumbnail": "",
    "count": 1000,
    "price": 100000
}

### RETRIEVE BOOK
GET {{baseProductUrl}}/books/product-1

### UPDATE BOOK
PUT {{baseProductUrl}}/books/product-0
Content-Type: application/json
Authorization: Token {{adminToken}}

{
  "id": 1,
  "title": "Muôn Kiếp Nhân Sinh",
  "author": 3,
  "genre": 1,
  "thumbnail": "https://www.vinabook.com/images/thumbnails/product/240x/372174_p93766m366182p93766mp93766e1muonkiepnhansinhphan201.jpg",
  "price": "99000.00"
}

### DELETE BOOK
DELETE {{baseProductUrl}}/books/muon-kiep-nhan-sinh
Content-Type: application/json
Authorization: Token {{adminToken}}

####################################################################

############################ PAYMENT ###############################

### GET ALL USER ORDER 
GET {{basePaymentUrl}}/order
Content-Type: application/json
Authorization: Token {{userToken}}

### CREATE ORDER
POST {{basePaymentUrl}}/order
Content-Type: application/json
Authorization: Token {{userToken}}

{
    "ship_date": "2022-12-23 12:00",
    "ship_place": "HCM",
    "note" : "giao hang tan noi",
    "is_paid": true,
    "paid_at": "paypal",
    "product": [
        { "book" : 1, "quantity" : 2}
    ]
}

### GET ORDER DETAIL
GET {{basePaymentUrl}}/order/15
Content-Type: application/json
Authorization: Token {{userToken}}

### UPDATE ORDER
PUT {{basePaymentUrl}}/order/15
Content-Type: application/json
Authorization: Token {{userToken}}

{
    "ship_date": "2012-04-23T18:25:43.511Z",
    "ship_place": "HCM",
    "note" : "giao hang tan noi",
    "is_paid": true,
    "paid_at": "paypal",
    "product": [
    {
        "book" : 1,
        "quantity" : 1,
    },
    {
        "book" : 2,
        "quantity" : 2
    }
    ]
}
### DELETE ORDER
DELETE  {{basePaymentUrl}}/order/1

### GET ALL ORDER
GET {{basePaymentUrl}}/all-order
Content-Type: application/json
Authorization: Token {{adminToken}}

####################################################################

############################ RATING ###############################

### GET ALL COMMENT AND RATING OF BOOK


### GET AVERAGE RATING OF BOOK


### VOTE AND COMMENT
POST {{baseProductUrl}}/books/product-2/rating
Content-Type: application/json
Authorization: Token {{userToken}}

{
    "rating": 5,
    "comment": "Thực sự hay"
}

### GET ALL COMMENT AND RATING
### To count number of specific vote point. FE need to sort this
GET {{baseProductUrl}}/books/product-2/rating
Content-Type: application/json

### GET RATING STATISTIC
GET {{baseProductUrl}}/books/product-2/rating-statistics
Content-Type: application/json

######################################################################

############################### CART #################################

### GET CART INFO 
GET {{basePaymentUrl}}/cart
Content-Type: application/json
Authorization: Token {{userToken}}

### CLEAR SHOPPING_SESSION
POST {{basePaymentUrl}}/cart
Content-Type: application/json
Authorization: Token {{userToken}}


### ADD BOOK TO CART
POST {{basePaymentUrl}}/cart/update
Content-Type: application/json
Authorization: Token {{userToken}}

{
    "book": 18,
    "quantity": 3
}

### REMOVE BOOK AWAY FROM CART
PUT {{basePaymentUrl}}/cart/update
Content-Type: application/json
Authorization: Token {{userToken}}

{
    "book": 15,
    "quantity": 3
}


