export const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO'
export const SET_LOADING_AI = 'SET_LOADING_AI'
export const RESET_ACCOUNT_INFO = 'RESET_ACCOUNT_INFO'
export const HANDLE_SHOW_LOGIN = 'HANDLE_SHOW_LOGIN'