export const ROUTE_HOME ='/'
export const ROUTE_REGISTER ='/register'
export const ROUTE_LIST_PRODUCTS ='/list-products/:slug'
export const ROUTE_BOOK_DETAIL ='/book-detail/:slug'
export const ROUTE_CART_PAGE ='/cart-page'
export const ROUTE_CONTROL_GENRE ='/control-genre'
export const ROUTE_PRODUCT_BOOK ='/product-book'