export const ROUTE_HOME ='/'
export const ROUTE_REGISTER ='/register'
export const ROUTE_LIST_PRODUCTS ='/list-products/:category'
export const ROUTE_BOOK_DETAIL ='/book-detail/:category'
export const ROUTE_CART_PAGE ='/cart-page'