# Generated by Django 4.1.1 on 2022-11-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_book_author_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='release',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
