# Generated by Django 4.1.1 on 2022-11-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_book_discount_book_release_alter_book_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
