export const GET_ALL_GENRE = 'GET_ALL_GENRE'
export const GET_ALL_GENRE_SUCCESS = 'GET_ALL_GENRE_SUCCESS'
export const GET_ALL_GENRE_FAIL = 'GET_ALL_GENRE_FAIL'

export const GET_ALL_AUTHOR = 'GET_ALL_AUTHOR'
export const GET_ALL_AUTHOR_SUCCESS = 'GET_ALL_AUTHOR_SUCCESS'
export const GET_ALL_AUTHOR_FAIL = 'GET_ALL_GENRE_FAIL'

export const GET_LIST_PRODUCT = 'GET_LIST_PRODUCT'  
export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS'  
export const GET_LIST_PRODUCT_FAIL = 'GET_LIST_PRODUCT_FAIL'

export const DELETE_GENRE = 'DELETE_GENRE'
export const ADD_GENRE = 'ADD_GENRE'

export const GET_RATING_STATISTICS = 'GET_RATING_STATISTICS'

export const GET_ALL_COMMENT = 'GET_ALL_COMMENT'
export const GET_ALL_COMMENT_SUCCESS = 'GET_ALL_COMMENT_SUCCESS'
export const GET_ALL_COMMENT_FAIL = 'GET_ALL_COMMENT_FAIL'

export const CREATE_RATING = 'CREATE_RATING'
export const CREATE_RATING_SUCCESS = 'CREATE_RATING_SUCCESS'
export const CREATE_RATING_FAIL = 'CREATE_RATING_FAIL'

export const GET_ALL_BOOK_ID = 'GET_ALL_BOOK_ID' 
export const GET_LIST_BOOKS_FROM_BOOK_ID = 'GET_LIST_BOOKS_FROM_BOOK_ID'

export const SET_LOADING_AI = 'SET_LOADING_AI'