export const GET_ALL_GENRE = 'GET_ALL_GENRE'
export const GET_ALL_GENRE_SUCCESS = 'GET_ALL_GENRE_SUCCESS'
export const GET_ALL_GENRE_FAIL = 'GET_ALL_GENRE_FAIL'

export const GET_LIST_PRODUCT_GENRE = 'GET_LIST_PRODUCT_GENRE'  
export const GET_LIST_PRODUCT_GENRE_SUCCESS = 'GET_LIST_PRODUCT_GENRE_SUCCESS'  
export const GET_LIST_PRODUCT_GENRE_FAIL = 'GET_LIST_PRODUCT_GENRE_FAIL'  