# Generated by Django 4.1.1 on 2022-11-27 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_alter_book_author_alter_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('ship_date', models.DateTimeField()),
                ('ship_place', models.CharField(max_length=500)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('is_paid', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('paid_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='product.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='payment.order')),
            ],
        ),
    ]
