# Generated by Django 4.1.1 on 2022-12-08 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_book_description_alter_author_about'),
        ('user', '0002_user_phone'),
        ('payment', '0005_alter_orderdetail_book_alter_orderdetail_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingSession',
            fields=[
                ('created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.book')),
                ('shopping_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='payment.shoppingsession')),
            ],
        ),
    ]
