# Generated by Django 4.1.1 on 2022-12-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_shoppingsession_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='shopping_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_session', to='payment.shoppingsession'),
        ),
    ]
