# Generated by Django 4.1.1 on 2022-12-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_cartitem_shopping_session'),
        ('payment', '0007_alter_cartitem_shopping_session_alter_order_paid_at_and_more'),
    ]

    operations = [
    ]
